
title = "Angel "
author = "Angel Pumacayo"
languageCode = "en-us"
theme =  "hugo-uno"
builddrafts = false
pygmentsuseclasses = true
PygmentsCodeFences = true

baseurl = "https://angelpumacayo10.github.io/email-blog/"

[Params]
  Author = "Angel Pumacayo"
  disqus = "disqusUsername"


